import os from "node:os";
import { randomUUID } from "node:crypto";
import type { GitHubClient } from "./client.js";

const PROCESS_BOOT_ID = randomUUID();
const PROCESS_STARTED_AT = new Date().toISOString();
const META_PREFIX = "<!-- night-shift:meta=";

export interface AutomationWriteContext {
  actor: "night-shift";
  source: "worker" | "specify-cli" | "implement-cli" | "review-cli";
  phase?: "specify" | "implement" | "review";
  runId?: string;
  profileId?: string;
  host: string;
  pid: number;
  processStartedAt: string;
  processBootId: string;
}

export function createAutomationWriteContext(
  source: AutomationWriteContext["source"],
  phase: AutomationWriteContext["phase"],
  runId?: string,
  profileId?: string,
): AutomationWriteContext {
  return {
    actor: "night-shift",
    source,
    ...(phase !== undefined ? { phase } : {}),
    ...(runId !== undefined ? { runId } : {}),
    ...(profileId !== undefined ? { profileId } : {}),
    host: os.hostname(),
    pid: process.pid,
    processStartedAt: PROCESS_STARTED_AT,
    processBootId: PROCESS_BOOT_ID,
  };
}

function renderMetadataLine(context: AutomationWriteContext): string {
  return `${META_PREFIX}${JSON.stringify(context)} -->`;
}

function renderVisibleFooter(context: AutomationWriteContext): string {
  const parts = [
    `source ${context.source}`,
    ...(context.phase ? [`phase ${context.phase}`] : []),
    ...(context.runId ? [`run ${context.runId}`] : []),
    `worker ${context.host}:${context.pid}`,
  ];
  return `_Generated by Night Shift (${parts.join(", ")})._`;
}

function appendIssueOrReviewMetadata(
  body: string,
  context: AutomationWriteContext,
): string {
  if (body.includes(META_PREFIX)) {
    return body;
  }
  return `${body}\n\n${renderVisibleFooter(context)}\n${renderMetadataLine(context)}`;
}

function appendLineCommentMetadata(
  body: string,
  context: AutomationWriteContext,
): string {
  if (body.includes(META_PREFIX)) {
    return body;
  }
  return `${body}\n\n${renderMetadataLine(context)}`;
}

export function withAutomationWriteContext(
  github: GitHubClient,
  context: AutomationWriteContext,
): GitHubClient {
  return {
    ...github,
    async upsertComment(issueNumber, markerId, body) {
      return github.upsertComment(
        issueNumber,
        markerId,
        appendIssueOrReviewMetadata(body, context),
      );
    },
    async upsertReviewComment(pullNumber, markerId, opts) {
      return github.upsertReviewComment(pullNumber, markerId, {
        ...opts,
        body: appendLineCommentMetadata(opts.body, context),
      });
    },
    async createReview(pullNumber, opts) {
      return github.createReview(pullNumber, {
        ...opts,
        body: appendIssueOrReviewMetadata(opts.body, context),
      });
    },
    async updateReview(pullNumber, reviewId, opts) {
      return github.updateReview(pullNumber, reviewId, {
        ...opts,
        body: appendIssueOrReviewMetadata(opts.body, context),
      });
    },
  };
}