import { describe, expect, it } from "vitest";
import { createInMemoryFakeGitHubClient } from "./fake.js";
import {
  createAutomationWriteContext,
  withAutomationWriteContext,
} from "../provenance.js";

describe("withAutomationWriteContext", () => {
  it("adds a visible footer and hidden metadata to issue comments", async () => {
    const github = createInMemoryFakeGitHubClient();
    github.seedIssue({ number: 1 });
    const wrapped = withAutomationWriteContext(
      github,
      createAutomationWriteContext("worker", "implement", "run-123", "default"),
    );

    await wrapped.upsertComment(1, "implement:summary", "body text");

    const comments = await github.listComments(1);
    expect(comments[0]!.body).toContain("Generated by Night Shift");
    expect(comments[0]!.body).toContain("run run-123");
    expect(comments[0]!.body).toContain("night-shift:meta=");
  });

  it("adds hidden metadata to review line comments without a visible footer", async () => {
    const github = createInMemoryFakeGitHubClient();
    const wrapped = withAutomationWriteContext(
      github,
      createAutomationWriteContext("worker", "review", "run-456", "default"),
    );

    await wrapped.upsertReviewComment(1, "review:finding", {
      path: "src/a.ts",
      line: 10,
      body: "line finding",
    });

    const comments = await github.listReviewComments(1);
    expect(comments[0]!.body).toContain("night-shift:meta=");
    expect(comments[0]!.body).not.toContain("Generated by Night Shift");
  });

  it("adds a visible footer and hidden metadata to PR reviews", async () => {
    const github = createInMemoryFakeGitHubClient();
    const wrapped = withAutomationWriteContext(
      github,
      createAutomationWriteContext("worker", "review", "run-789", "default"),
    );

    await wrapped.createReview(1, {
      event: "COMMENT",
      body: "review summary",
    });

    const reviews = await github.listReviews(1);
    expect(reviews[0]!.body).toContain("Generated by Night Shift");
    expect(reviews[0]!.body).toContain("night-shift:meta=");
  });
});